### ISSUE TITLE
 'The requested module '/node_modules/@antv_ava.js' does not provide an export named 'statistics''

### ISSUE THREAD

**Issue by helxsz** [antvis/AVA#788]
* **Package Name**:
  "@antv/ava"
* **Package Version**:
    "^3.4.1",

* **Platform**:
   MAC ,vue3 
* **Mini Showcase(like screenshots)**:
![Screenshot 2024-07-26 at 15 07 51](https://github.com/user-attachments/assets/c5dbcf23-3b31-4f13-8e1e-b8f1bdf0d373)

* **CodePen Link**:

can't work on the statistic package even from the tutorial 

```
import { statistics as stats } from '@antv/ava';
stats.min([1, 2, 3, 201, 999, 4, 5, 10]);
```

**Comment by chenluli** [comment]
In v3.x version, the methods in statistics are directly exported from `@antv/ava`, as shown in the example below:
```
import { min  } from '@antv/ava';
/** Calculate minimum */
min([1, 2, 3, 201, 999, 4, 5, 10]);
```
https://ava.antv.antgroup.com/en/guide/migrate/tov3fromv2#insight
<img width="1161" alt="Screenshot 2024-07-29 at 10 38 30" src="https://github.com/user-attachments/assets/041eee20-46ac-4778-9de6-c4ca9fedad1b">

Thanks for your feedback, we apologize for any inconvenience caused by the outdated documentation of our data API. We will be updating the documentation to the new version very soon.
